url: http://restfb.com
baseurl: 

# Site settings
title: 
  default: restfb
  light: <span class="restfb-brand light">rest</span><span class="restfb-brand highlight">fb</span>
  dark: <span class="restfb-brand dark">rest</span><span class="restfb-brand highlight">fb</span>
description: "RestFB is a simple and flexible Facebook Graph API client written in Java. It contains support for the Facebook Messenger Platform and the Facebook Marketing API."

# code and explanantion
collections:
  documentation:
    title: Documentation
    render: true
    output: true

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 337ab7
  secondary: 337ab7  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Mark Allen
  pic: 1
  position: Founder
  social:
    - title: github
      url: https://github.com/revetkn
    - title: linkedin
      url: http://www.linkedin.com/pub/mark-allen/1/b75/721/

- name: Norbert Bartels
  pic: 2
  position: Maintainer and Lead Developer
  social:
    - title: github
      url: https://github.com/nbartels
    - title: stack-overflow
      url: http://stackoverflow.com/users/1379528/norbert
    - title: xing
      url: https://www.xing.com/profile/Norbert_Bartels2

- name: many Contributors
  pic: 3

# site Social network links and types (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/Restfb-909653922461664
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/restfb
  - title: github
    url: http://github.com/restfb/restfb
  - title: envelope
    url: http://groups.google.com/group/restfb

# additional links
navigation:
  - text: Cookbook
    url: /cookbook/
  - text: Documentation
    url: /documentation/

clients:
   - name: Angry Birds
     url: https://apps.facebook.com/angrybirds/
     pic: img/clients/angry-birds-friends.min.png
   - name: Hubspot
     url: http://www.hubspot.com/
     pic: img/clients/hubspot.min.png
   - name: Atchik Services
     url: http://www.atchik-services.com
     pic: img/clients/atchikservices.min.png
   - name: Lithium
     url: http://www.lithium.com/
     pic: img/clients/lithium.min.png
   - name: ITyX Solutions AG
     url: https://www.ityxsolutions.com/
     pic: img/clients/ityx.min.png
   - name: Nitro AI
     url: http://nitro.ai
     pic: img/clients/nitro-ai.min.png
   - name: Dwinq
     url: http://dwinq.com/
     pic: img/clients/dwinq.min.png
   - name: Sematell GmbH
     url: http://www.sematell.com/
     pic: img/clients/sematell.min.png	
   - name: Perka, Inc.
     url: https://perka.com/
     pic: img/clients/perka.min.png	 
   - name: The Socialstation
     url: http://thesocialstation.com/
     pic: img/clients/thesocialstation.color.jpg
   - name: Sparkcentral
     url: https://www.sparkcentral.com/
     pic: img/clients/sparkcentral.min.png
   - name: Falcon.io
     url: https://www.falcon.io/
     pic: img/clients/falconio.min.png 
   - name: Friend2Friend
     url: http://www.friend2friend.com/
     pic: img/clients/friend2friend.min.png
   - name: Tynamo
     url: http://www.tynamo.org/
     pic: img/clients/tynamo.min.png
   - name: IBM
     url: http://www.ibm.com/
     pic: img/clients/ibm.min.png
   - name: nukesuite
     url: https://www.nukesuite.com/
     pic: img/clients/nukesuite.min.png

gems:
  - jekyll-sitemap

sass:
  style: compressed

usecdn: true

# Build settings
markdown: kramdown
permalink: pretty

exclude: [README.md, LICENSE]